name: Cache to Artifact

on:
  pull_request: # This will run the workflow for every push to an open pull request.
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      cacheKey:
        description: 'Cache Key Hash'
        required: true

jobs:
  cache-to-artifact:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Restore cache
      uses: actions/cache@v2
      with:
        path: image.tar
        key: ghcr.io/kreneskyp/ix/nodejs:f908460311841699fd55a12f4ece8802

    - name: Archive cache
      run: |
        tar -czf cache.f908460311841699fd55a12f4ece8802.tar.gz image.tar

    - name: Upload cache as artifact
      uses: actions/upload-artifact@v2
      with:
        name: cache-artifact
        path: cache.f908460311841699fd55a12f4ece8802.tar.gz
