name: Publish Dev

# run on merge
# Testing note: if testing this against PRs note that this will always fail in a PR
#               the first time because the image doesn't exist yet. Re-running the
#               workflow after `build` job has run will succeed.
on:
  push:
    branches: [master]


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # setup
      - name: Checkout
        uses: actions/checkout@v3

      # build javascript - This will build the image an extra time because it's needed locally
      - name: run
        shell: bash
        env:
          NO_IMAGE_BUILD: 1
        run: |
          touch .env
          make frontend

      # docker build + publish
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/kreneskyp/ix/sandbox:dev