name: Publish
on:
  release:
    types:
      - created

env:
  IMAGE_NAME: ghcr.io/kreneskyp/ix/sandbox

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # setup
      - name: Checkout
        uses: actions/checkout@v3

      - name: Load image url
        id: load_image_url
        run: |
          IMAGE_URL=`make image-url`
          echo "image-url=$IMAGE_URL" >> "$GITHUB_OUTPUT"

      - name: Restore Cache
        uses: actions/cache@v2
        id: restore_cache
        with:
          path: image.tar
          key: ${{ steps.load_image_url.outputs.image-url }}

      # build local image - NodeJS image must be built locally a because it's needed to build the frontend.
      #                     The cache wasn't working reliably across workflows, so it must be built here. This
      #                     build is not multi-platform since it is needed locally.
      - name: Build Docker image
        id: build
        if: steps.restore_cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p .sentinel
          IMAGE_URL=`make image-url-nodejs`
          echo "Building NodeJS Docker image: $IMAGE_URL"
          make image
          docker save $IMAGE_URL > image.tar

      # transpile javascript frontend - output will be added to image
      - name: run
        shell: bash
        env:
          NO_IMAGE_BUILD: 1
        run: |
          touch .env
          make frontend

      # docker multi-platform build + publish
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v8
          push: true
          tags: ghcr.io/kreneskyp/ix/sandbox:latest ghcr.io/kreneskyp/ix/sandbox:${{ github.event.release.tag_name }}
