name: Publish Dev

# run on merge
# Testing note: if testing this against PRs note that this will always fail in a PR
#               the first time because the image doesn't exist yet. Re-running the
#               workflow after `build` job has run will succeed.
on:
  push:
    branches: [master]


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # setup
      - name: Checkout
        uses: actions/checkout@v3

      - name: Load image url
        id: load_image_url
        run: |
          IMAGE_URL=`make image-url`
          echo "image-url=$IMAGE_URL" >> "$GITHUB_OUTPUT"

      - name: Restore Cache
        uses: actions/cache@v2
        id: restore_cache
        with:
          path: image.tar
          key: ${{ steps.load_image_url.outputs.image-url }}

      # build local image - Image must be built locally a first time because it's needed to build the frontend.
      #                     The cache wasn't working reliably across workflows, so it must be built here. This
      #                     build is not multi-platform since it is needed locally.
      - name: Build Docker image
        id: build
        if: steps.restore_cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p .sentinel
          IMAGE_URL=`make image-url`
          echo "Building Docker image: $IMAGE_URL"
          make image
          docker save $IMAGE_URL > image.tar

      # docker build + publish
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/kreneskyp/ix/sandbox:dev