name: Publish Dev
on:
  pull_request:
    types: [ opened, synchronize ]
  push:
    branches: [main]


jobs:
  docker:
    runs-on: ubuntu-latest
    # TODO depends?
    steps:
      # setup
      - name: Checkout
        uses: actions/checkout@v3

      # Load or build cached image
      - name: Load image url
        id: load_image_url
        run: |
          IMAGE_URL=`make image-url`
          echo "image-url=$IMAGE_URL" >> "$GITHUB_OUTPUT"
      - name: Restore Cache
        uses: actions/cache@v2
        id: restore_cache
        with:
          path: image.tar
          key: ${{ steps.load_image_url.outputs.image-url }}
      - name: load image
        shell: bash
        run: |
          docker load --input image.tar
          docker tag ${{ steps.load_image_url.outputs.image-url }} ghcr.io/kreneskyp/ix/sandbox:latest

      # build javascript - Reuse the cached image from the CI workflow. A local image is needed for the
      #                    command. It's faster to use the image that was already built.
      - name: run
        shell: bash
        env:
          NO_IMAGE_BUILD: 1
        run: |
          touch .env
          make frontend

      # docker build + publish
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/kreneskyp/ix/sandbox:dev